image: erlang

before_script:
  - mix deps.get

stages:
  - build
  - test

job1:
  stage: build
  script:
    - mix deps.compile
    - mix compile
  only:
    - master

job2:
  stage: test
  script: mix test
  only:
    - master
